# Generated by Django 5.1 on 2024-09-30 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
