# Generated by Django 5.1 on 2024-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_password_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True, default="No bio for this user.", max_length=500
            ),
        ),
    ]
