# Generated by Django 5.1 on 2024-09-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="delivery_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pickup", "Pickup Only"),
                    ("delivery", "Delivery Available"),
                    ("both", "Pickup or Delivery"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
