# Generated by Django 5.1 on 2024-09-04 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_alter_listing_delivery_option"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
