# Generated by Django 5.1 on 2024-09-09 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_listing_favorited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("item_sale", "Item for Sale"),
                    ("item_free", "Free Item"),
                    ("item_wanted", "Item Wanted"),
                    ("service", "Service"),
                    ("job", "Job"),
                    ("housing", "Housing"),
                    ("event", "Event"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("like_new", "Like New"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="delivery_option",
            field=models.CharField(
                choices=[
                    ("pickup", "Pickup Only"),
                    ("delivery", "Delivery Available"),
                    ("both", "Pickup or Delivery"),
                    ("na", "Not Applicable"),
                ],
                default="na",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Price"),
                    ("negotiable", "Negotiable"),
                    ("free", "Free"),
                    ("contact", "Contact for Price"),
                ],
                default="fixed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="listings.subcategory",
            ),
        ),
    ]
